package io.github.saalfy.sur.ui.theme

import androidx.compose.ui.graphics.Color

// Calm teal palette, used on Android 8-11 (Android 12+ uses dynamic color).
// Every surface/container role is set explicitly so nothing falls back to the M3 baseline purple.
val LightPrimary = Color(0xFF2B6A6C)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB0EEF0)
val LightOnPrimaryContainer = Color(0xFF002021)
val LightInversePrimary = Color(0xFF94D1D3)
val LightSecondary = Color(0xFF4A6364)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCCE8E9)
val LightOnSecondaryContainer = Color(0xFF051F20)
val LightTertiary = Color(0xFF4B607C)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFD3E4FF)
val LightOnTertiaryContainer = Color(0xFF041C35)
val LightSurface = Color(0xFFF5FAFA)
val LightOnSurface = Color(0xFF171D1D)
val LightSurfaceVariant = Color(0xFFDAE5E5)
val LightOnSurfaceVariant = Color(0xFF3F4949)
val LightSurfaceDim = Color(0xFFD5DBDB)
val LightSurfaceBright = Color(0xFFF5FAFA)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFEFF5F5)
val LightSurfaceContainer = Color(0xFFE9EFEF)
val LightSurfaceContainerHigh = Color(0xFFE3E9E9)
val LightSurfaceContainerHighest = Color(0xFFDDE4E4)
val LightInverseSurface = Color(0xFF2B3232)
val LightInverseOnSurface = Color(0xFFECF2F2)
val LightOutline = Color(0xFF6F7979)
val LightOutlineVariant = Color(0xFFBEC8C9)

val DarkPrimary = Color(0xFF94D1D3)
val DarkOnPrimary = Color(0xFF003739)
val DarkPrimaryContainer = Color(0xFF004F52)
val DarkOnPrimaryContainer = Color(0xFFB0EEF0)
val DarkInversePrimary = Color(0xFF2B6A6C)
val DarkSecondary = Color(0xFFB1CCCD)
val DarkOnSecondary = Color(0xFF1C3435)
val DarkSecondaryContainer = Color(0xFF334B4C)
val DarkOnSecondaryContainer = Color(0xFFCCE8E9)
val DarkTertiary = Color(0xFFB3C8E8)
val DarkOnTertiary = Color(0xFF1C314B)
val DarkTertiaryContainer = Color(0xFF334863)
val DarkOnTertiaryContainer = Color(0xFFD3E4FF)
val DarkSurface = Color(0xFF0E1415)
val DarkOnSurface = Color(0xFFDDE4E4)
val DarkSurfaceVariant = Color(0xFF3F4949)
val DarkOnSurfaceVariant = Color(0xFFBEC8C9)
val DarkSurfaceDim = Color(0xFF0E1415)
val DarkSurfaceBright = Color(0xFF343A3B)
val DarkSurfaceContainerLowest = Color(0xFF090F0F)
val DarkSurfaceContainerLow = Color(0xFF171D1D)
val DarkSurfaceContainer = Color(0xFF1B2121)
val DarkSurfaceContainerHigh = Color(0xFF252B2B)
val DarkSurfaceContainerHighest = Color(0xFF303636)
val DarkInverseSurface = Color(0xFFDDE4E4)
val DarkInverseOnSurface = Color(0xFF2B3232)
val DarkOutline = Color(0xFF899393)
val DarkOutlineVariant = Color(0xFF3F4949)
